import fs from 'node:fs';
import path from 'node:path';
import { chromium, webkit, devices } from 'playwright';
const [baseline,candidate]=process.argv.slice(2);if(!baseline||!candidate)throw new Error('usage: perf.mjs baseline candidate');
const outDir=process.env.PERF_ARTIFACT_DIR||'perf-artifacts';fs.mkdirSync(outDir,{recursive:true});
const results={baseline:{},candidate:{}};
function statsHook(page){return page.addInitScript(()=>{window.__perf={long:[]};try{new PerformanceObserver((list)=>{for(const e of list.getEntries())window.__perf.long.push({start:e.startTime,duration:e.duration});}).observe({type:'longtask',buffered:true});}catch(_){}});}
async function waitCore(page,timeout=150000){const t=Date.now();await page.waitForFunction(()=>window.__matsuyamaViewer&&!window.__matsuyamaViewer.isDestroyed(),null,{timeout});await page.waitForFunction(()=>window.MatsuyamaImmersive?.debug().tilesetAttached===true,null,{timeout});await page.waitForFunction(()=>document.querySelector('#terrainStatus')?.textContent.includes('DEM10B'),null,{timeout});return Date.now()-t;}
async function frameSamples(page,ms=3500){return await page.evaluate(async(ms)=>{const a=[];let last=performance.now(),end=last+ms;while(performance.now()<end){await new Promise(requestAnimationFrame);const now=performance.now();a.push(now-last);last=now;}return a;},ms);}
async function inputSamples(page,n=16){return await page.evaluate(async(n)=>{const out=[],w=window.MatsuyamaWalk;for(let i=0;i<n;i++){const before=w.state.cameraHeading,t=performance.now();w.setVirtualStick('look',.75,0);await new Promise((resolve)=>{const check=()=>{if(Math.abs(w.state.cameraHeading-before)>1e-5)resolve();else requestAnimationFrame(check);};check();});out.push(performance.now()-t);w.setVirtualStick('look',0,0);await new Promise(requestAnimationFrame);}return out;},n);}
async function freezeWater(page){await page.evaluate(()=>{const p=window.__matsuyamaViewer.scene.primitives;for(let i=0;i<p.length;i++){const u=p.get(i)?.appearance?.material?.uniforms;if(u&&'animationSpeed' in u)u.animationSpeed=0;}window.__matsuyamaViewer.scene.requestRender();window.__matsuyamaViewer.render();});}
async function fixedView(page){await page.evaluate(()=>{const v=window.__matsuyamaViewer,C=window.Cesium;v.camera.setView({destination:C.Cartesian3.fromDegrees(132.7657,33.8392,650),orientation:{heading:0,pitch:-Math.PI/2,roll:0}});v.scene.requestRender();});await page.waitForTimeout(5000);}
async function demSamples(page){return await page.evaluate(async()=>{const C=window.Cesium,v=window.__matsuyamaViewer,pts=[[132.7657,33.8392],[132.7863,33.8518],[132.7514,33.8392],[132.715,33.788],[132.718,33.864]].map(([lon,lat])=>C.Cartographic.fromDegrees(lon,lat));const r=await C.sampleTerrain(v.terrainProvider,14,pts);return r.map(x=>x.height);});}
async function runVariant(browserType,contextOpts,url,label,variant){const browser=browserType==='chromium'?await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=swiftshader']}):await webkit.launch({headless:true});const context=await browser.newContext(contextOpts);const page=await context.newPage();await statsHook(page);const requests=[];page.on('response',r=>requests.push({url:r.url(),status:r.status(),len:Number(r.headers()['content-length']||0)}));const navStart=Date.now();await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await waitCore(page);const coldReady=Date.now()-navStart;await page.waitForFunction(()=>/^3D水面：/.test(document.querySelector('#water3dStatus')?.textContent||''),null,{timeout:90000});await fixedView(page);const staticFrames=await frameSamples(page);const dem=await demSamples(page);const waterStatus=await page.locator('#water3dStatus').textContent();await freezeWater(page);await page.screenshot({path:path.join(outDir,`${variant}-${label}-scene.png`),animations:'disabled',timeout:90000});await page.evaluate(()=>window.MatsuyamaWalk.start());await page.waitForFunction(()=>window.MatsuyamaWalk?.state?.active===true);await page.waitForTimeout(700);const walkFramesPromise=frameSamples(page);await page.evaluate(()=>window.MatsuyamaWalk.setVirtualStick('move',0,.9));await page.waitForTimeout(2800);await page.evaluate(()=>window.MatsuyamaWalk.setVirtualStick('move',0,0));const walkFrames=await walkFramesPromise;const input=inputSamples(page);const turnFramesPromise=frameSamples(page);await page.evaluate(()=>window.MatsuyamaWalk.setVirtualStick('look',.8,.25));await page.waitForTimeout(2800);await page.evaluate(()=>window.MatsuyamaWalk.setVirtualStick('look',0,0));const turnFrames=await turnFramesPromise;const inputLatency=await input;await page.evaluate(()=>window.MatsuyamaWalk.stop());const longTasks=await page.evaluate(()=>window.__perf.long.slice());const heap=await page.evaluate(()=>performance.memory?performance.memory.usedJSHeapSize:null);const debug=await page.evaluate(()=>window.MatsuyamaImmersive.debug());await page.reload({waitUntil:'domcontentloaded',timeout:120000});const warmReady=await waitCore(page);await browser.close();return{coldReady,warmReady,staticFrames,walkFrames,turnFrames,inputLatency,longTasks,dem,waterStatus,debug,network:{requests:requests.length,contentLength:requests.reduce((s,x)=>s+(x.len||0),0),buildingRiskRequests:requests.filter(x=>x.url.includes('building-risk.json')).length,waterJsonRequests:requests.filter(x=>/water3d\/(flood|tsunami)\.json/.test(x.url)).length},heap};}
const configs=[['chromium',{viewport:{width:1440,height:900},deviceScaleFactor:1},'desktop'],['webkit',{...devices['iPhone 15']},'iphone']];
for(const [browserType,opts,label] of configs){results.baseline[label]=await runVariant(browserType,opts,baseline,label,'baseline');results.candidate[label]=await runVariant(browserType,opts,candidate,label,'candidate');}
fs.writeFileSync(path.join(outDir,'raw.json'),JSON.stringify(results));console.log('PERF RAW COMPLETE');
